### ISSUE TITLE
Blockbook: Websocket failed to reconnect

### ISSUE THREAD

**Issue by kaladinlight** [shapeshift/unchained#899]
### Overview

Recent increase in restarts due to the api being unable to reconnect with the blockbook websocket. I am guessing this is more related to our reconnect logic than and actual blockbook problem...

### References and additional details

```bash
{"error":{},"fn":"ws.onerror","message":"websocket error","timestamp":"2023-12-07T10:33:51.123Z","namespace":"unchained:blockbook","status":"error"}
{"code":1006,"reason":"","fn":"ws.close","message":"websocket closed","timestamp":"2023-12-07T10:33:51.123Z","namespace":"unchained:blockbook","status":"error"}
{"error":{},"fn":"ws.onerror","message":"websocket error","timestamp":"2023-12-07T10:33:56.123Z","namespace":"unchained:blockbook","status":"error"}
{"code":1006,"reason":"","fn":"ws.close","message":"websocket closed","timestamp":"2023-12-07T10:33:56.123Z","namespace":"unchained:blockbook","status":"error"}
/app/node/packages/blockbook/dist/websocket.js:24
                throw new Error('failed to reconnect');
                ^

Error: failed to reconnect
    at WebsocketClient.initialize (/app/node/packages/blockbook/dist/websocket.js:24:23)
    at WebsocketClient.close (/app/node/packages/blockbook/dist/websocket.js:43:14)
    at socket.onclose (/app/node/packages/blockbook/dist/websocket.js:35:18)
    at WebSocket.onClose (/app/node/packages/blockbook/node_modules/ws/lib/event-target.js:210:18)
    at WebSocket.emit (node:events:513:28)
    at WebSocket.emitClose (/app/node/packages/blockbook/node_modules/ws/lib/websocket.js:248:12)
    at emitErrorAndClose (/app/node/packages/blockbook/node_modules/ws/lib/websocket.js:994:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

### Acceptance Criteria

- No more restarts due to websocket reconnect

**Comment by kaladinlight** [comment]
Closed by https://github.com/shapeshift/unchained/pull/908
